# Generated by Django 2.2 on 2020-02-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_sentimentmessageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentmessageitem',
            name='sentiment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sentimentmessageitem',
            name='translation',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
